// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sentriq-admin-cockpit-alerts/WorkbenchAlerts.tsx": () => import("../components/mockups/sentriq-admin-cockpit-alerts/WorkbenchAlerts.tsx"),
  "./components/mockups/sentriq-admin-cockpit-collapsed/AdminCockpitCollapsed.tsx": () => import("../components/mockups/sentriq-admin-cockpit-collapsed/AdminCockpitCollapsed.tsx"),
  "./components/mockups/sentriq-alert-briefing/AlertBriefing.tsx": () => import("../components/mockups/sentriq-alert-briefing/AlertBriefing.tsx"),
  "./components/mockups/sentriq-admin-cockpit/AdminCockpit.tsx": () => import("../components/mockups/sentriq-admin-cockpit/AdminCockpit.tsx")
};
